# -*- coding: utf-8 -*-
"""
수하물 신호등 — 항공사 규정

이 파일만 고치고 `python3 _build.py` 를 실행하면 판별기의 항공사 목록이 갱신됩니다.

한 줄 형식
  {"id": 짧은키, "name": 이름, "code": 편명코드, "tag": 그룹,
   "cabinKg": 기내무게, "cabinSize": 기내크기, "cabinCnt": 기내개수,
   "checkedKg": 위탁무료, "checkedSize": 위탁크기, "checkedNote": 메모,
   "extra": 하단 한 줄, "link": 공식 규정 주소}

tag 는 선택 상자의 그룹 제목이 됩니다. 같은 그룹끼리 붙여서 적으세요.
숫자는 모두 국제선 이코노미 기본 운임 기준입니다.
"""

AIRLINES = [
# ── 국적 대형항공사 ─────────────────────────
{"id":"ke","name":"대한항공","code":"KE","tag":"국적 대형항공사",
 "cabinKg":"10kg","cabinSize":"55×40×20cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"미주 노선은 2개까지",
 "extra":"일등석·프레스티지석은 기내 2개 총 18kg",
 "link":"https://www.koreanair.com/contents/plan-your-travel/baggage/carry-on-baggage"},
{"id":"oz","name":"아시아나항공","code":"OZ","tag":"국적 대형항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개(40×30×20cm)",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"미주 노선은 2개까지",
 "extra":"비즈니스석은 기내 2개(각 10kg) + 소지품 1개",
 "link":"https://m.flyasiana.com/C/KR/KO/contents/carry-on-baggage"},

# ── 국적 하이브리드 ─────────────────────────
{"id":"yp","name":"에어프레미아","code":"YP","tag":"국적 하이브리드",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"운임별","checkedSize":"이코노미 라이트는 무료 위탁 없음","checkedNote":"스탠다드 이상 1개 23kg",
 "extra":"운임 등급 차이가 큰 항공사라 예약 내역 확인이 필수",
 "link":"https://www.airpremia.com"},

# ── 국적 저비용항공사 ───────────────────────
{"id":"7c","name":"제주항공","code":"7C","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm · 가장 긴 변 55cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"베이직 운임은 무료 위탁 없음",
 "extra":"국내선은 위탁 15kg 기준, 운임별로 다름",
 "link":"https://www.jejuair.net/ko/linkService/boardingProcessGuide/cabinBaggage.do"},
{"id":"lj","name":"진에어","code":"LJ","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"괌 노선은 2개, 각 23kg",
 "extra":"노선별로 무료 허용량이 다르니 예약 내역 확인",
 "link":"https://www.jinair.com"},
{"id":"tw","name":"트리니티항공 (구 티웨이)","code":"TW","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15~20kg","checkedSize":"1개 · 노선별 상이","checkedNote":"장거리 노선은 2개, 각 23kg",
 "extra":"2026년 9월 10일 사명 변경, 편명 코드 TW 유지",
 "link":"https://www.trinityairways.com"},
{"id":"bx","name":"에어부산","code":"BX","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"일부 노선 2개, 각 23kg",
 "extra":"특가 항공권은 무료 위탁이 빠질 수 있어요",
 "link":"https://www.airbusan.com"},
{"id":"rs","name":"에어서울","code":"RS","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"일부 노선 2개, 각 23kg",
 "extra":"특가 운임은 무료 위탁 제외",
 "link":"https://flyairseoul.com"},
{"id":"rf","name":"에어로케이","code":"RF","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"55×40×20cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개",
 "checkedKg":"15~20kg","checkedSize":"1개 · 삼변 합 277cm 미만","checkedNote":"Plus 20kg · Basic 15kg · Lite 무료 없음",
 "extra":"청주 기반 신생 LCC. Lite 운임은 위탁을 따로 사야 합니다",
 "link":"https://www.aerok.com"},
{"id":"ze","name":"이스타항공","code":"ZE","tag":"국적 저비용항공사",
 "cabinKg":"10kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"15kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"할인 운임은 별도 구매",
 "extra":"국내선은 위탁 15kg 기준",
 "link":"https://www.eastarjet.com"},

# ── 일본 항공사 ─────────────────────────────
{"id":"nh","name":"ANA (전일본공수)","code":"NH","tag":"일본 항공사",
 "cabinKg":"10kg","cabinSize":"55×40×25cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg × 2개","checkedSize":"삼변 합 158cm 이내","checkedNote":"노선·등급별로 상이",
 "extra":"일본 국내선 소형기(100석 미만)는 기내 규정이 더 작아요",
 "link":"https://www.ana.co.jp/ko/kr/travel-information/baggage-information/carry-on/"},
{"id":"jl","name":"JAL (일본항공)","code":"JL","tag":"일본 항공사",
 "cabinKg":"10kg","cabinSize":"55×40×25cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg × 2개","checkedSize":"삼변 합 203cm 이내","checkedNote":"이코노미 기준",
 "extra":"100석 미만 기종은 기내 수하물 크기 기준이 달라요",
 "link":"https://www.jal.co.jp/kr/ko/inter/baggage/checked/"},
{"id":"mm","name":"피치항공","code":"MM","tag":"일본 항공사",
 "cabinKg":"7kg","cabinSize":"55×40×25cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"유료","checkedSize":"20kg부터 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"기내 7kg는 가방과 소지품을 합친 무게예요",
 "link":"https://www.flypeach.com/kr"},
{"id":"zg","name":"집에어 (ZIPAIR)","code":"ZG","tag":"일본 항공사",
 "cabinKg":"7kg","cabinSize":"55×40×25cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"운임별","checkedSize":"요금제에 따라 0~3개","checkedNote":"기본 요금은 무료 위탁 없음",
 "extra":"JAL 계열 중장거리 LCC. 예약 시 수하물 옵션을 꼭 확인하세요",
 "link":"https://www.zipair.net"},

{"id":"ij","name":"스프링재팬","code":"IJ","tag":"일본 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"유료","checkedSize":"요금제에 따라 옵션 구매","checkedNote":"기본 운임은 무료 위탁 없음",
 "extra":"JAL 계열 중국계 LCC. 인천–도쿄 노선 운항",
 "link":"https://jp.ch.com"},

# ── 중화권 항공사 ───────────────────────────
{"id":"cx","name":"캐세이퍼시픽항공","code":"CX","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"20~30kg","checkedSize":"운임 등급별 상이","checkedNote":"이코노미 라이트는 적게 배정",
 "extra":"무게 합산 방식이라 가방 개수 제한은 없습니다",
 "link":"https://www.cathaypacific.com/cx/ko_KR.html"},
{"id":"ci","name":"중화항공 (차이나에어라인)","code":"CI","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"미주 노선은 2개 23kg",
 "extra":"아시아 노선은 무게제, 미주 노선은 개수제입니다",
 "link":"https://www.china-airlines.com/kr/ko"},
{"id":"br","name":"에바항공","code":"BR","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"미주 노선은 2개 23kg",
 "extra":"기내 7kg는 가방과 소지품을 합친 무게예요",
 "link":"https://www.evaair.com/ko-kr/index.html"},
{"id":"jx","name":"스타룩스항공","code":"JX","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"대만 신생 항공사. 인천–타이베이 노선 운항",
 "link":"https://www.starlux-airlines.com"},
{"id":"mu","name":"중국동방항공","code":"MU","tag":"중화권 항공사",
 "cabinKg":"8kg","cabinSize":"55×40×20cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"한·중 노선 이코노미 기준",
 "extra":"라이트 이코노미 운임은 무료 위탁이 없을 수 있어요",
 "link":"https://kr.ceair.com/newCMS/kr/ko/content/ko_Header/headerBottom/service_1/baggageService/"},
{"id":"cz","name":"중국남방항공","code":"CZ","tag":"중화권 항공사",
 "cabinKg":"5kg","cabinSize":"55×40×20cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"한·중 노선 이코노미 기준",
 "extra":"기내 5kg로 국적사(10kg)의 절반입니다. 무게를 꼭 재 보세요",
 "link":"https://www.csair.com/mcms/mcmsNewSite/ko/kr/build/index.html?page=xlgd"},
{"id":"ca","name":"중국국제항공 (에어차이나)","code":"CA","tag":"중화권 항공사",
 "cabinKg":"5kg","cabinSize":"55×40×20cm · 삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"노선별 상이",
 "extra":"기내 5kg 제한이 엄격한 편입니다. 노트북은 개인 소지품으로 분리하세요",
 "link":"https://www.airchina.kr/KR/KO/info/carry-on-baggage"},
{"id":"uo","name":"홍콩익스프레스항공","code":"UO","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"유료","checkedSize":"20kg부터 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"캐세이 계열 LCC. 기내 무게를 게이트에서 재는 편입니다",
 "link":"https://www.hkexpress.com/ko-kr/"},

{"id":"it","name":"타이거에어 타이완","code":"IT","tag":"중화권 항공사",
 "cabinKg":"10kg","cabinSize":"54×38×23cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"20kg","checkedSize":"1개 · 삼변 합 203cm 이내","checkedNote":"타이거 라이트는 무료 위탁 없음",
 "extra":"기내 10kg로 LCC 중에서는 넉넉한 편입니다",
 "link":"https://www.tigerairtw.com/kr/welcome-on-board/baggage"},
{"id":"hb","name":"그레이터베이항공","code":"HB","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"20~40kg","checkedSize":"무게 합산 · 삼변 합 158cm 이내","checkedNote":"GO GO 20kg · Value 30kg · 프로모는 무료 없음",
 "extra":"홍콩 신생 항공사. 운임 이름이 GO 계열로 나뉩니다",
 "link":"https://www.greaterbay-airlines.com/hk/en_HK/manage/our-services/baggage.html"},
{"id":"hx","name":"홍콩항공","code":"HX","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"운임별","checkedSize":"삼변 합 158cm 이내","checkedNote":"예약 내역에서 확인하세요",
 "extra":"운임 등급 차이가 커서 공식 페이지 확인을 권합니다",
 "link":"https://www.hongkongairlines.com"},
{"id":"9c","name":"춘추항공","code":"9C","tag":"중화권 항공사",
 "cabinKg":"7kg","cabinSize":"40×30×20cm","cabinCnt":"가방 1개",
 "checkedKg":"유료","checkedSize":"옵션 구매","checkedNote":"기본 운임은 무료 위탁 없음",
 "extra":"기내 규격이 작은 편이라 기내용 캐리어도 걸릴 수 있습니다",
 "link":"https://kr.ch.com"},

# ── 동남아 항공사 ───────────────────────────
{"id":"sq","name":"싱가포르항공","code":"SQ","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"삼변 합 115cm 이내","cabinCnt":"가방 1개 + 소지품 1개(40×30×10cm)",
 "checkedKg":"25~30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"무게 합산이라 가방 개수는 자유롭습니다",
 "link":"https://www.singaporeair.com/ko_KR/kr/home"},
{"id":"tg","name":"타이항공","code":"TG","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×45×25cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"20~30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"이코노미 기본 운임은 20kg인 경우가 많습니다",
 "link":"https://www.thaiairways.com/ko_KR"},
{"id":"vn","name":"베트남항공","code":"VN","tag":"동남아 항공사",
 "cabinKg":"10kg","cabinSize":"56×36×23cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"운임 등급별 상이",
 "extra":"2025년 5월 이후 발권분은 이코노미 기내 총 10kg 기준",
 "link":"https://www.vietnamairlines.com/kr/ko/travel-information/baggage/baggage-allowance-hand-baggage"},
{"id":"vj","name":"비엣젯항공","code":"VJ","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"유료","checkedSize":"20kg부터 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"공항에서 사면 크게 비싸니 예약 때 미리 구매하세요",
 "link":"https://www.vietjetair.com"},
{"id":"pr","name":"필리핀항공","code":"PR","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"미주 노선은 2개",
 "extra":"운임 등급에 따라 무료 위탁이 없을 수 있습니다",
 "link":"https://www.philippineairlines.com"},
{"id":"5j","name":"세부퍼시픽항공","code":"5J","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 소지품 1개(35×25×20cm)",
 "checkedKg":"유료","checkedSize":"20~40kg 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"기내 7kg는 가방과 소지품을 합친 무게예요",
 "link":"https://www.cebupacificair.com"},
{"id":"ak","name":"에어아시아","code":"AK","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 소지품 1개(40×30×10cm)",
 "checkedKg":"유료","checkedSize":"15~30kg 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"공항에서 사면 비싸니 예약 때 미리 구매하세요",
 "link":"https://www.airasia.com"},
{"id":"tr","name":"스쿠트항공","code":"TR","tag":"동남아 항공사",
 "cabinKg":"10kg","cabinSize":"54×38×23cm (2개 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"유료","checkedSize":"20kg부터 옵션 구매","checkedNote":"기본 운임은 무료 위탁 없음",
 "extra":"싱가포르항공 계열 LCC. 기내는 10kg로 넉넉한 편",
 "link":"https://www.flyscoot.com/ko"},
{"id":"mh","name":"말레이시아항공","code":"MH","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"이코노미 기본 운임 기준 30kg으로 넉넉한 편",
 "link":"https://www.malaysiaairlines.com"},
{"id":"ga","name":"가루다인도네시아항공","code":"GA","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"인천–자카르타·발리 노선 운항",
 "link":"https://www.garuda-indonesia.com"},

{"id":"xj","name":"타이 에어아시아 엑스","code":"XJ","tag":"동남아 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 소지품 1개(40×30×10cm)",
 "checkedKg":"유료","checkedSize":"20kg부터 옵션 구매","checkedNote":"무료 위탁 수하물 없음",
 "extra":"인천–방콕 중거리 노선. 에어아시아 그룹 공통 규정",
 "link":"https://www.airasia.com"},

# ── 중동·유럽 항공사 ────────────────────────
{"id":"ek","name":"에미레이트항공","code":"EK","tag":"중동·유럽 항공사",
 "cabinKg":"7kg","cabinSize":"55×38×20cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"20~35kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"스페셜 20 · 세이버 25 · 플렉스 30kg",
 "extra":"무게 합산이라 가방을 여러 개로 나눠 담아도 됩니다",
 "link":"https://www.emirates.com/kr/korean/"},
{"id":"qr","name":"카타르항공","code":"QR","tag":"중동·유럽 항공사",
 "cabinKg":"7kg","cabinSize":"50×37×25cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"25~35kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"운임 등급별 상이",
 "extra":"비즈니스석은 기내 2개 총 15kg",
 "link":"https://www.qatarairways.com/ko-kr/homepage.html"},
{"id":"tk","name":"터키항공","code":"TK","tag":"중동·유럽 항공사",
 "cabinKg":"8kg","cabinSize":"55×40×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"비즈니스는 개당 32kg",
 "extra":"이스탄불 경유로 유럽 가는 노선이 많습니다",
 "link":"https://www.turkishairlines.com/ko-kr/"},
{"id":"lh","name":"루프트한자 독일항공","code":"LH","tag":"중동·유럽 항공사",
 "cabinKg":"8kg","cabinSize":"55×40×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"이코노미 라이트는 무료 위탁 없음",
 "extra":"운임 등급 이름이 라이트·클래식·플렉스로 나뉩니다",
 "link":"https://www.lufthansa.com/kr/ko/homepage"},
{"id":"ey","name":"에티하드항공","code":"EY","tag":"중동·유럽 항공사",
 "cabinKg":"7kg","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 노트북 가방 1개",
 "checkedKg":"운임별","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"예약 내역에서 확인하세요",
 "extra":"아부다비 경유 유럽·아프리카 노선",
 "link":"https://www.etihad.com/en-us/help/baggage-information"},
{"id":"af","name":"에어프랑스","code":"AF","tag":"중동·유럽 항공사",
 "cabinKg":"12kg","cabinSize":"55×35×25cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"라이트 운임은 무료 위탁 없음",
 "extra":"기내 12kg로 유럽 항공사 중에서는 넉넉한 편",
 "link":"https://wwws.airfrance.co.kr"},
{"id":"kl","name":"KLM 네덜란드항공","code":"KL","tag":"중동·유럽 항공사",
 "cabinKg":"12kg","cabinSize":"55×35×25cm (가방+소지품 합계)","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"라이트 운임은 무료 위탁 없음",
 "extra":"에어프랑스와 같은 그룹이라 규정이 동일합니다",
 "link":"https://www.klm.co.kr"},
{"id":"lo","name":"LOT 폴란드항공","code":"LO","tag":"중동·유럽 항공사",
 "cabinKg":"8kg","cabinSize":"55×40×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"이코노미 세이버는 무료 위탁 없음",
 "extra":"바르샤바 경유 동유럽 노선",
 "link":"https://www.lot.com/kr/ko"},
{"id":"ay","name":"핀에어","code":"AY","tag":"중동·유럽 항공사",
 "cabinKg":"8kg","cabinSize":"55×40×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"라이트 운임은 무료 위탁 없음",
 "extra":"헬싱키 경유 북유럽 노선",
 "link":"https://www.finnair.com/kr-ko"},

# ── 미주 항공사 ─────────────────────────────
{"id":"dl","name":"델타항공","code":"DL","tag":"미주 항공사",
 "cabinKg":"무게 제한 없음","cabinSize":"56×35×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"베이직 이코노미는 유료",
 "extra":"미국 항공사는 기내 수하물 무게를 재지 않고 크기만 봅니다",
 "link":"https://ko.delta.com"},
{"id":"ua","name":"유나이티드항공","code":"UA","tag":"미주 항공사",
 "cabinKg":"무게 제한 없음","cabinSize":"56×35×22cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"베이직 이코노미는 유료",
 "extra":"미국 항공사는 기내 수하물 무게를 재지 않고 크기만 봅니다",
 "link":"https://www.united.com/ko/kr"},
{"id":"aa","name":"아메리칸항공","code":"AA","tag":"미주 항공사",
 "cabinKg":"무게 제한 없음","cabinSize":"56×36×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"베이직 이코노미는 유료",
 "extra":"미국 항공사는 기내 수하물 무게를 재지 않고 크기만 봅니다",
 "link":"https://www.american-airlines.co.kr"},
{"id":"ac","name":"에어캐나다","code":"AC","tag":"미주 항공사",
 "cabinKg":"무게 제한 없음","cabinSize":"55×40×23cm","cabinCnt":"가방 1개 + 개인 소지품 1개",
 "checkedKg":"23kg","checkedSize":"1개 · 삼변 합 158cm 이내","checkedNote":"베이직 운임은 유료",
 "extra":"기내 수하물은 크기만 확인합니다",
 "link":"https://www.aircanada.com/kr/ko/aco/home.html"},

# ── 대양주 항공사 ───────────────────────────
{"id":"qf","name":"콴타스항공","code":"QF","tag":"대양주 항공사",
 "cabinKg":"7kg × 2개","cabinSize":"56×36×23cm","cabinCnt":"가방 2개 (합계 14kg)",
 "checkedKg":"30kg","checkedSize":"무게 합산 · 개당 32kg 이내","checkedNote":"미주 노선은 1개 32kg",
 "extra":"기내 2개까지 허용해 아시아 항공사보다 넉넉합니다",
 "link":"https://www.qantas.com/kr/ko/travel-info/baggage/checked-baggage.html"},
]
